spring.application.name=Criaturas
# Puerto del servidor (opcional)
server.port=8080
# Configuración de la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://dpg-d6p8homa2pns73f8njs0-a.frankfurt-postgres.render.com:5432/juegosdb_y9h5
spring.datasource.username=juegosuser
spring.datasource.password=odt6sTQjzg4zDdHD5j5umh5rOl0oClqu
spring.datasource.driver-class-name=org.postgresql.Driver
# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Log del Hikari (Pool de conexiones)
# Con este atributo en modo DEBUG da información del POOL
logging.level.com.zaxxer.hikari=DEBUG
# Pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5